### ISSUE TITLE
404 on dev.to URL : generate-database-diagrams-with-github-actions-workflows

### ISSUE THREAD

**Issue by HakumenNC** [HakumenNC/docker-schemacrawler-reporting#13]
@adriens,
Error 404 on URL : https://dev.to/sualeh/generate-database-diagrams-with-github-actions-workflows-4l96=

**Comment by adriens** [comment]
https://www.linkedin.com/posts/adrien-sales_schemacrawler-16115-activity-6730973782388944896-OZNl
