### ISSUE TITLE
This is the Vagrant way

### ISSUE THREAD

**Issue by HakumenNC** [HakumenNC/docker-schemacrawler-reporting#5]
Experiments and add the [Vagrant](https://www.vagrantup.com/) way to use docker-schemacrawler-reporting.

**Comment by adriens** [comment]
J'aimerais bien m'y coller au moins un peu demain 🙏

**Comment by mbarre** [comment]
je m'y colle ;)

**Comment by HakumenNC** [comment]
Nickel !
